"""Add language property to word entity

Revision ID: 63758d3e5234
Revises: 8324f2f4b9c2
Create Date: 2025-04-07 18:40:34.416293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63758d3e5234'
down_revision: Union[str, None] = '8324f2f4b9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('word', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=56), autoincrement=False, nullable=False),
    sa.Column('definition', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('sentence', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('phonetics', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('sentence_audio', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('partial_sentence', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('singular', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('singular_audio', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('plural', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('plural_audio', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('synonyms', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('image_2', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='words_pkey')
    )
    # ### end Alembic commands ###
